export interface PrBodyFileEntry {
  path: string;
  format: 'json' | 'md';
}

export interface BuildPrBodyInput {
  commitMessage: string;
  files: PrBodyFileEntry[];
  pluginVersion: string;
  figmaFileUrl: string;
  figmaFileName: string;
  contractKind: string;
}

function formatLabel(format: 'json' | 'md'): string {
  if (format === 'json') {
    return 'JSON (machine)';
  }
  return 'Markdown (human)';
}

export function buildPrBody(input: BuildPrBodyInput): string {
  const lines: string[] = [input.commitMessage, '', '## Files', '', '| Path | Format |', '| ---- | ------ |'];

  for (let i = 0; i < input.files.length; i++) {
    const file = input.files[i];
    lines.push('| `' + file.path + '` | ' + formatLabel(file.format) + ' |');
  }

  lines.push(
    '',
    '---',
    '',
    '_Generated by FigHub v' + input.pluginVersion + '_',
    '',
    '**Source Figma file:** [' + input.figmaFileName + '](' + input.figmaFileUrl + ')',
    '',
    '**Contract kind:** `' + input.contractKind + '`',
  );

  return lines.join('\n');
}

export function buildDriftReportPrTitle(
  summary: import('@detroitlabs/fighub-contracts').DriftReportSummary,
  sprintLabel?: string,
): string {
  let title =
    'DesignOps drift: ' +
    String(summary.push) +
    ' push, ' +
    String(summary.pull) +
    ' pull, ' +
    String(summary.conflict) +
    ' conflicts';
  if (sprintLabel !== undefined && sprintLabel.length > 0) {
    title += ' (' + sprintLabel + ')';
  }
  return title;
}
