import { describe, expect, it } from 'vitest';

import { buildPrBody } from '@/io/github/prBody';

describe('buildPrBody', () => {
  it('matches the PR body template snapshot', () => {
    const body = buildPrBody({
      commitMessage: 'fighub: drift-report export (2026-05-27)',
      files: [
        { path: 'docs/fighub/drift-report-2026-05-27.v1.json', format: 'json' },
        { path: 'docs/fighub/drift-report-2026-05-27.v1.md', format: 'md' },
      ],
      pluginVersion: '0.4.0',
      figmaFileUrl: 'https://www.figma.com/design/abc123/My%20Design%20File',
      figmaFileName: 'My Design File',
      contractKind: 'drift-report',
    });

    expect(body).toMatchInlineSnapshot(`
      "fighub: drift-report export (2026-05-27)

      ## Files

      | Path | Format |
      | ---- | ------ |
      | \`docs/fighub/drift-report-2026-05-27.v1.json\` | JSON (machine) |
      | \`docs/fighub/drift-report-2026-05-27.v1.md\` | Markdown (human) |

      ---

      _Generated by FigHub v0.4.0_

      **Source Figma file:** [My Design File](https://www.figma.com/design/abc123/My%20Design%20File)

      **Contract kind:** \`drift-report\`"
    `);
  });
});
