export function buildCodeConnectPrBody(input: {
  stubPaths: readonly string[];
  figmaFileUrl: string;
  pluginVersion: string;
}): string {
  const lines: string[] = ['FigHub Code Connect stubs', '', '## Stubs', ''];

  for (let i = 0; i < input.stubPaths.length; i++) {
    lines.push('- `' + input.stubPaths[i] + '`');
  }

  lines.push(
    '',
    '## After merge',
    '',
    'Run `npx figma connect publish` in CI (or locally) to publish mappings to Figma.',
    '',
    '---',
    '',
    '_Generated by FigHub v' + input.pluginVersion + '_',
    '',
    '**Source Figma file:** ' + input.figmaFileUrl,
  );

  return lines.join('\n');
}
